services:
  db:
    image: postgres:latest
    container_name: postgres_farmacia_int2
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: mydb
    ports:
      - "5499:5432"
